version: "3"

services:
  url-backend:
    build: ./server
    stdin_open: true
    ports:
      - "9000:9000"
    restart: unless-stopped
  url-frontend:
    build: ./client
    ports:
      - "3000:3000"
    restart: unless-stopped
