#
# Copyright (c) 2021 - Present. Blend Labs, Inc. All rights reserved
# Blend Confidential - Restricted
#
version: '3.3'

services:
  postgres:
    image: postgres:11.6
    ports:
      - 5432
    environment:
      - POSTGRES_USER=service_app
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=service

  test:
    build:
      context: ..
      dockerfile: server/Dockerfile.test
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=service
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=service_app
      - NODE_ENV=test
    command: ['./scripts/dockerWaitForPostgres.sh', 'postgres', '5432', 'npm', 'run', 'testRaw']
